// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 02 Oct 2019 23:23:21 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lzfse provides Go bindings for lzfse.
*/
package lzfse
